import type { Metadata } from "next";
import Navbar from "@/components/layout/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LangLayout({
  children,
  params,
}: any) {
  const { lang } = params;

  return (
    <>
      <Navbar />
      {children}
    </>
  );
}
