import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import HtmlAttributes from "@/components/HtmlAttributes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body suppressHydrationWarning>
        <HtmlAttributes />
        <Toaster />
        {children}
      </body>
    </html>
  );
}
